repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.7.6
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --expand-star-imports
          - --remove-all-unused-imports
          - --remove-unused-variables
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade
#  - repo: local
#    hooks:
#      - id: pytest
#        name: pytest
#        language: system
#        entry: python3 -m pytest "tests" -p no:warnings --cov="app"
#        types: [python]
#        stages: [ commit ]
#        pass_filenames: false
#        always_run: true
default_language_version:
  python: python3.10
